Write-Host "========================================"
Write-Host "  Starting Backend + Frontend"
Write-Host "========================================"
Write-Host ""
Write-Host "Backend: http://localhost:8081"
Write-Host "Frontend: http://localhost:3000"
Write-Host ""
Write-Host "Open TWO PowerShell windows:"
Write-Host ""
Write-Host "Window 1 (Backend):"
Write-Host "  cd demo-backend"
Write-Host "  mvn org.springframework.boot:spring-boot-maven-plugin:3.4.4:run"
Write-Host ""
Write-Host "Window 2 (Frontend):"
Write-Host "  cd demo-frontend"
Write-Host "  npx vite --host"
